routes:
  # Главная страница - статическая (index.hbs)
  /:
    template: index

  # Блог перемещается на /blog (home.hbs)
  /blog/main/:
    template: home
    controller: channel
    filter: tag:[Blog]
  /blog/growth/:
    template: home
    controller: channel
    filter: tag:[Growth]
  /blog/projects/:
    template: home
    controller: channel
    filter: tag:[Projects]


collections:
  /blog/thoughts/:
    permalink: /thoughts/{slug}/
    # template: index
    template: home
    filter: primary_tag:[thoughts]
  # Посты остаются на корневом уровне /{slug}/
  /blog/:
    permalink: /{slug}/
    template: home
    filter: 'primary_tag:-[thoughts]'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
